services:
  stats-client:
    build:
      context: ./stat_clnt
      dockerfile: Dockerfile
    environment:
      STATS_SERVER_URL: http://stats-server:9090
    depends_on:
      - stats-server
    networks:
      - stats-net

  stats-server:
    build:
      context: ./stat_srvc
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - stats-db
    networks:
      - stats-net

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_stats:/var/lib/postgresql/data
    networks:
      - stats-net

volumes:
  pgdata_stats:

networks:
  stats-net:
