server.port=8080

management.endpoints.web.exposure.include=health

spring.datasource.url=jdbc:postgresql://main-db:5432/ewm_main
spring.datasource.username=ewm_user
spring.datasource.password=ewm_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

logging.level.ru.practicum=INFO
logging.level.org.hibernate=WARN
